package org.koitharu.kotatsu.backups.data.mihon

import android.content.Context
import android.net.Uri
import androidx.room.withTransaction
import dagger.Reusable
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.flow.FlowCollector
import kotlinx.serialization.SerializationException
import kotlinx.serialization.protobuf.ProtoBuf
import okio.buffer
import okio.gzip
import okio.source
import org.koitharu.kotatsu.core.db.MangaDatabase
import org.koitharu.kotatsu.core.db.entity.MangaEntity
import org.koitharu.kotatsu.core.db.entity.TagEntity
import org.koitharu.kotatsu.favourites.data.FavouriteCategoryEntity
import org.koitharu.kotatsu.favourites.data.FavouriteEntity
import org.koitharu.kotatsu.history.data.HistoryEntity
import org.koitharu.kotatsu.list.domain.ListSortOrder
import java.io.IOException
import java.util.zip.GZIPInputStream
import javax.inject.Inject

@Reusable
class MihonImportRepository @Inject constructor(
	@ApplicationContext private val context: Context,
	private val database: MangaDatabase,
) {

	private val protoBuf = ProtoBuf {
		encodeDefaults = false
	}

	suspend fun importBackup(
		uri: Uri,
		progressCollector: FlowCollector<MihonImportState>?,
	): MihonImportResult {
		progressCollector?.emit(MihonImportState.Loading("Reading backup file…"))

		val backup = decodeBackup(uri)
		val sourceMap = backup.backupSources.associate { it.sourceId to it.name }

		var importedMangaCount = 0
		var importedCategoriesCount = 0
		var importedHistoryCount = 0
		val unmappedSourcesSet = mutableSetOf<String>()

		val totalManga = backup.backupManga.size

		// 1. Process Categories inside a transaction
		val categoryIdMap = mutableMapOf<Long, Long>() // Mihon categoryId -> Kotatsu categoryId
		database.withTransaction {
			val existingCategories = database.getFavouriteCategoriesDao().findAll()
			for (category in backup.backupCategories) {
				val existing = existingCategories.find { it.title.equals(category.name, ignoreCase = true) }
				if (existing != null) {
					categoryIdMap[category.id] = existing.categoryId.toLong()
				} else {
					val newSortKey = database.getFavouriteCategoriesDao().getNextSortKey()
					val newCategory = FavouriteCategoryEntity(
						categoryId = 0, // Auto-generated by Room
						createdAt = System.currentTimeMillis(),
						sortKey = newSortKey,
						title = category.name,
						order = ListSortOrder.NEWEST.name,
						track = true,
						isVisibleInLibrary = true,
						deletedAt = 0L,
					)
					val insertedId = database.getFavouriteCategoriesDao().insert(newCategory)
					categoryIdMap[category.id] = insertedId
					importedCategoriesCount++
				}
			}
		}

		// 2. Process Manga
		for ((index, manga) in backup.backupManga.withIndex()) {
			progressCollector?.emit(
				MihonImportState.Progress(
					current = index + 1,
					total = totalManga,
					title = manga.title.ifEmpty { "Manga #${index + 1}" },
				)
			)

			val sourceName = sourceMap[manga.source]
			val resolvedSource = MihonSourceMapper.resolveKotatsuSource(
				mihonSourceId = manga.source,
				mihonSourceName = sourceName,
				mangaUrl = manga.url,
				thumbnailUrl = manga.thumbnailUrl,
			)

			if (resolvedSource.startsWith("MIHON_") || resolvedSource == sourceName) {
				if (!sourceName.isNullOrEmpty()) {
					unmappedSourcesSet.add(sourceName)
				}
			}

			val mangaId = (resolvedSource + ":" + manga.url).hashCode().toLong()

			val mangaEntity = MangaEntity(
				id = mangaId,
				title = manga.title,
				altTitles = null,
				url = manga.url,
				publicUrl = manga.url,
				rating = -1f,
				isNsfw = false,
				contentRating = null,
				coverUrl = manga.thumbnailUrl.orEmpty(),
				largeCoverUrl = manga.thumbnailUrl,
				state = null,
				authors = manga.author ?: manga.artist,
				source = resolvedSource,
			)

			val tagEntities = manga.genre.map { genreTitle ->
				val tagKey = genreTitle.lowercase().trim()
				val tagId = (resolvedSource + ":" + tagKey).hashCode().toLong()
				TagEntity(
					id = tagId,
					title = genreTitle.trim(),
					key = tagKey,
					source = resolvedSource,
					isPinned = false,
				)
			}

			database.withTransaction {
				// Upsert tags & manga
				if (tagEntities.isNotEmpty()) {
					database.getTagsDao().upsert(tagEntities)
				}
				database.getMangaDao().upsert(mangaEntity, tagEntities)

				// Process Favourites
				if (manga.favorite) {
					if (manga.categories.isNotEmpty()) {
						for (catId in manga.categories) {
							val targetCatId = categoryIdMap[catId] ?: 0L
							database.getFavouritesDao().upsert(
								FavouriteEntity(
									mangaId = mangaId,
									categoryId = targetCatId,
									sortKey = 0,
									isPinned = false,
									createdAt = if (manga.dateAdded > 0) manga.dateAdded else System.currentTimeMillis(),
									deletedAt = 0L,
								)
							)
						}
					} else {
						database.getFavouritesDao().upsert(
							FavouriteEntity(
								mangaId = mangaId,
								categoryId = 0L,
								sortKey = 0,
								isPinned = false,
								createdAt = if (manga.dateAdded > 0) manga.dateAdded else System.currentTimeMillis(),
								deletedAt = 0L,
							)
						)
					}
				}

				// Process History
				val lastHistory = manga.history.maxByOrNull { it.lastRead }
				val readChapter = manga.chapters.filter { it.read || it.lastPageRead > 0 }.maxByOrNull { it.lastPageRead }

				if (lastHistory != null || readChapter != null) {
					val chapterUrl = lastHistory?.url ?: readChapter?.url.orEmpty()
					val chapterId = chapterUrl.hashCode().toLong()
					val page = readChapter?.lastPageRead?.toInt() ?: 0
					val lastReadTime = lastHistory?.lastRead ?: System.currentTimeMillis()

					val historyEntity = HistoryEntity(
						mangaId = mangaId,
						createdAt = lastReadTime,
						updatedAt = lastReadTime,
						chapterId = chapterId,
						page = page,
						scroll = 0f,
						percent = 0f,
						deletedAt = 0L,
						chaptersCount = manga.chapters.size,
					)
					database.getHistoryDao().upsert(historyEntity)
					importedHistoryCount++
				}

				importedMangaCount++
			}
		}

		val result = MihonImportResult(
			importedMangaCount = importedMangaCount,
			importedCategoriesCount = importedCategoriesCount,
			importedHistoryCount = importedHistoryCount,
			unmappedSources = unmappedSourcesSet.toList(),
		)

		progressCollector?.emit(MihonImportState.Completed(result))
		return result
	}

	private fun decodeBackup(uri: Uri): MihonBackup {
		val inputStream = context.contentResolver.openInputStream(uri)
			?: throw IOException("Unable to open file stream")

		val byteArray = inputStream.use { stream ->
			val source = stream.source().buffer()
			val peeked = source.peek()
			if (peeked.request(2)) {
				val magic = peeked.readShort().toInt() and 0xFFFF
				if (magic == 0x1f8b) { // GZIP magic
					source.gzip().buffer().use { it.readByteArray() }
				} else {
					source.readByteArray()
				}
			} else {
				source.readByteArray()
			}
		}

		return try {
			protoBuf.decodeFromByteArray(MihonBackup.serializer(), byteArray)
		} catch (e: Exception) {
			throw IOException("Not a valid Mihon or Tachiyomi backup file", e)
		}
	}
}
